server:
  port: 80

spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: events
          uri: http://localhost:8080
          predicates:
            - Path=/events/**
        - id: exercise
          uri: http://localhost:8080
          predicates:
            - Path=/exercise/**
        - id: events
          uri: http://localhost:8080
          predicates:
            - Path=/exercise/**
        - id: registration
          uri: http://localhost:8081
          predicates:
            - Path=/registration
          filters:
            - RewritePath=/registration, /auth
        - id: token
          uri: http://localhost:8081
          predicates:
            - Path=/login
          filters:
            - RewritePath=/login, /auth/token